#! /usr/bin/env php

<?php
use Symfony\Component\Console\Application;
use Vulcan\Rivescript\Console\ChatCommand;
use Vulcan\Rivescript\Parser;
use Vulcan\Rivescript\Rivescript;

require 'vendor/autoload.php';

$app        = new Application('Rivescript PHP Interpreter', '1.0');
$rivescript = new Rivescript;

$app->add(new ChatCommand($rivescript));

$app->run();
