#!/usr/bin/php
<?php
/**
 * rivescript-cli
 *
 * This app allows you to load your scripts from the
 * command line and test them.
 *
 * PHP version 8.0 and higher.
 *
 * @category Core
 * @package  Development
 * @author   Johnny Mast <mastjohnny@gmail.com>
 * @license  https://opensource.org/licenses/MIT MIT
 * @link     https://github.com/axiom-labs/rivescript-php
 * @since    0.4.0
 */


require 'vendor/autoload.php';

use Axiom\Rivescript\Rivescript;
use Symfony\Component\Console\Application;
use Axiom\Rivescript\Console\RivescriptInterpreter;

$app = new Application('Rivescript PHP Interpreter', '2.0');

$app->add(new RivescriptInterpreter(new Rivescript));
$app->run();