#! /usr/bin/env php

<?php

require 'vendor/autoload.php';

use Vulcan\Rivescript\Rivescript;
use Symfony\Component\Console\Application;
use Vulcan\Rivescript\Console\ChatCommand;

$app        = new Application('Rivescript PHP Interpreter', '2.0');
$rivescript = new Rivescript;

$app->add(new ChatCommand($rivescript));

$app->run();